name: drl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pip:
      - torch>=2.0.0
      - gymnasium>=0.28.1
      - stable-baselines3>=2.0.0
      - sb3-contrib
      - pybullet>=3.2.0
      - tensorboard
      - pyyaml
      - pybullet-planning
      - matplotlib
      - pandas
